feat: mapping TCP ports

diff --git a/bin/tcp-map-ports b/bin/tcp-map-ports
--- a/bin/tcp-map-ports
+++ b/bin/tcp-map-ports
@@ -1,100 +1,105 @@
 #!/usr/bin/env bash
 
-SCRIPT="${BASH_SOURCE[0]:-$0}"
 set -euo pipefail
+SCRIPT="$0"
 
 usage() {
     cat <<eof
-Uses socat to remap a set of ports locally.
+Map the TCP traffic on a local port to another local port or to a remote host
 
 Usage:
-    $SCRIPT [--check | --echo] LISTEN1:TARGET1 [ LISTEN2:TARGET2 ... ]
-    $SCRIPT [--check | --echo] 'LISTEN1:TARGET1,LISTEN2:TARGET2,...'
-    $SCRIPT [--check | --echo] 'LISTEN1:TARGET1 LISTEN2:TARGET2,...'
+    $SCRIPT [ -p PATH | -s] LISTEN_PORT:TARGET_PORT ...
+    $SCRIPT [ -p PATH | -s] LISTEN_PORT:REMOTE_HOST:REMOTE_PORT ...
 
 Options:
-    -h, --help   this help
-    --check      just check if there's a process listening
-    --echo       just print port mappings, one line each
+    LISTEN_PORT               port to listen locally
+    TARGET_PORT               local port to forward the traffic to
+    REMOTE_HOST:REMOTE_PORT   remote host:port to forward the traffic to
+    -p, --pids-file=<PATH>    file to append the process PIDs to
+    -s, --sudo                run the mapping process with 'sudo'
 eof
 }
 
-CHECK=false
-ECHO=false
-PORT_SPECS=()
+LISTEN_PORT=
+TARGET_HOST=
+TARGET_PORT=
+PIDS_FILE=
+SUDO=
 
-main() {
-    for spec in "${PORT_SPECS[@]}"; do
-        IFS=: read -r listen_port target_port <<<"$spec"
+setup_mapping() {
+    if [ "$TARGET_HOST" = 'localhost' ] && [ "$LISTEN_PORT" = "$TARGET_PORT" ]; then
+        echo >&2 "INFO: listen port :$LISTEN_PORT is equal to local target port, nothing to map"
+        return 0
+    fi
 
-        if [ "$CHECK" = 'true' ]; then
-            if ! netstat -ltpn | grep -q ":$listen_port "; then
-                echo >&2 "ERROR: nothing listening on pair $spec"
-                exit 1
-            else
-                echo >&2 "OK: $spec"
-            fi
-        elif [ "$ECHO" = 'true' ]; then
-            echo "$spec"
-        else
-            nohup socat -d "TCP-LISTEN:$listen_port,fork" "TCP:localhost:$target_port" &
-            pid="$!"
-            echo >&2 "INFO: forwarding TCP port $listen_port to port $target_port on localhost (pid: $pid)"
-        fi
-    done
+    $SUDO socat -d "TCP-LISTEN:$LISTEN_PORT,fork" "TCP:$TARGET_HOST:$TARGET_PORT" &
+    pid="$!"
+    disown -h
+
+    if [ -n "$PIDS_FILE" ]; then
+        echo "$pid" >> "$PIDS_FILE"
+    fi
+
+    echo >&2 "INFO: mapping :$LISTEN_PORT to $TARGET_HOST:$TARGET_PORT (pid: $pid)"
 }
 
-if ! ARGS="$(getopt -o 'h' --long 'help,check,echo' -- "$@")"; then
-    usage >&2
-    exit 1
-fi
+parse_spec() {
+    local spec="$1"
 
-eval set -- "$ARGS"
+    if [[ "$spec" =~ ^([0-9]+):([0-9]+)$ ]]; then
+        LISTEN_PORT="${BASH_REMATCH[1]}"
+        TARGET_HOST=localhost
+        TARGET_PORT="${BASH_REMATCH[2]}"
+    elif [[ "$spec" =~ ^([0-9]+):([a-zA-Z0-9.-]+):([0-9]+)$ ]]; then
+        LISTEN_PORT="${BASH_REMATCH[1]}"
+        TARGET_HOST="${BASH_REMATCH[2]}"
+        TARGET_PORT="${BASH_REMATCH[3]}"
+    else
+        echo >&2 "ERROR: invalid mapping spec '$spec'"
+        return 1
+    fi
+
+    if [ "$TARGET_HOST" = '127.0.0.1' ]; then
+        TARGET_HOST=localhost
+    fi
+}
+
+# parse the command line
+OPTS="$(getopt -l help,pids-file:,sudo -o hp:s -n "$SCRIPT" -- "$@")"
+eval set -- "$OPTS"
 
 while true; do
-    case "$1" in
-    -h | --help )
+    case "${1:-}" in
+    -h | --help)
         usage
-        exit 0
-        ;;
-    --check )
-        CHECK=true
+        exit 0;;
+    -p | --pids-file)
+        PIDS_FILE="${2:-}"
+        if [ -z "$PIDS_FILE" ]; then
+            echo >&2 "ERROR: no PID file specified"
+            exit 1
+        fi
+        shift 2;;
+    -s | --sudo)
+        SUDO=sudo
+        shift;;
+    --)
         shift
-        ;;
-    --echo )
-        ECHO=true
-        shift
-        ;;
-    -- )
-        shift
-        break
-        ;;
-    * )
-        usage >&2
-        echo >&2
-        echo >&2 "ERROR: unrecognized argument $1"
-        exit 1
-        ;;
+        break;;
     esac
 done
 
-if [ "$CHECK" = 'true' ] && [ "$ECHO" = 'true' ]; then
-    echo >&2 "ERROR: --check and --echo are mutually exclusive"
-    exit 1
+if [ "$#" -lt 1 ]; then
+    echo >&2 "WARN: no ports to map"
+    exit 0
 fi
 
-IFS=' ' read -ra PORT_SPECS <<<"${*//,/ }"
-
-if [[ "${#PORT_SPECS[@]}" -eq 0 ]]; then
-    echo >&2 "ERROR: no port specified"
-    exit 1
-fi
-
-for spec in "${PORT_SPECS[@]}"; do
-    if [[ ! "$spec" =~ ^([0-9]+):([0-9]+)$ ]]; then
-        echo >&2 "ERROR: bad port spec '$spec'"
-        exit 1
-    fi
+# before starting anything, check if all mappings are valid
+for arg; do
+    parse_spec "$arg"
 done
 
-main
+for spec; do
+    parse_spec "$spec"
+    setup_mapping
+done
